print("what fruit am I storing?")
fruit=input()
if apples:
    print('bin 1')
elif oranges:
    print('bin 2')
elif olives:
    print('bin 3')
else:
    print('error! I do not regonise this fruit')
    
    
